encoder: resnet50
inchannels: 4096
outchannels: 2
attention: coam
coam_layer_data: [3, [2048, 1024, 512], [256, 128, 64]]
lr: 0.0001
weight_decay: 0.0005
batch_size: 16
test_batch_size: 1
num_dataloader_workers: 2
datasets:
  train_dataset:
    name: coco_train
    class: InpatinedCocoDataset
    args:
      path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/train'
      split: "train"
      method: "centernet"
      image_transformation: "affine"
      change: True
  val_dataset:
    name: coco_val
    class: InpatinedCocoDataset
    args:
      path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/train'
      split: "val"
      method: "centernet"
      image_transformation: "affine"
      change: True
  test_datasets:
    # - name: coco_test_small
    #   class: InpatinedCocoDataset
    #   args:
    #     path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/test/small'
    #     split: "test"
    #     method: "centernet"
    #     image_transformation: "affine"
    # - name: coco_test_medium
    #   class: InpatinedCocoDataset
    #   args:
    #     path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/test/medium'
    #     split: "test"
    #     method: "centernet"
    #     image_transformation: "affine"
    # - name: coco_test_large
    #   class: InpatinedCocoDataset
    #   args:
    #     path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/test/large'
    #     split: "test"
    #     method: "centernet"
    #     image_transformation: "affine"
    #     change: False
    # - name: synthtext
    #   class: SynthTextDataset
    #   args:
    #     path_to_dataset: '/home/hung/difference_localization/dataset/synthtext_change'
    #     split: "test"
    #     method: "centernet"
    #     image_transformation: "identity"
    #     change: False
    # - name: std
    #   class: StdDataset
    #   args:
    #     path_to_dataset: '/home/hung/difference_localization/dataset/std'
    #     split: "test"
    #     method: "centernet"
    #     image_transformation: "projective"
    #     change: False
    - name: kubric
      class: KubricChange
      args:
        path_to_dataset: '/home/hung/difference_localization/dataset/kubric-change'
        split: "test"
        method: "centernet"
        image_transformation: "projective"
        change: False
    # - name: coco_test_all
    #   class: ConcatDataset
    #   datasets:
    #     - name: coco_test_small
    #       class: InpatinedCocoDataset
    #       args:
    #         path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/test/small'
    #         split: "test"
    #         method: "centernet"
    #         image_transformation: "affine"
    #         change: True
    #     - name: coco_test_medium
    #       class: InpatinedCocoDataset
    #       args:
    #         path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/test/medium'
    #         split: "test"
    #         method: "centernet"
    #         image_transformation: "affine"
    #         change: True
    #     - name: coco_test_large
    #       class: InpatinedCocoDataset
    #       args:
    #         path_to_dataset: '/home/hung/difference_localization/dataset/coco_inpainted/test/large'
    #         split: "test"
    #         method: "centernet"
    #         image_transformation: "affine"
    #         change: True
